extra_hosts:

  i0:
            - "peer0.org1.example.com:158.37.63.164"
            - "peer1.org1.example.com:158.37.63.165"
            - "peer2.org1.example.com:158.37.63.175"

  i1:
            - "orderer0.example.com:158.39.75.116"
            - "orderer1.example.com:158.39.75.116"
            - "orderer2.example.com:158.39.75.116"
            - "ca.example.com:158.39.75.116"
            - "peer0.org1.example.com:158.37.63.164"
            - "peer1.org1.example.com:158.37.63.165"
            - "peer2.org1.example.com:158.37.63.175"

  i2:


  i3: